/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-primary-container": "#005f26",
        "secondary": "#006094",
        "surface-container-high": "#b5f0c2",
        "secondary-fixed-dim": "#8ec9ff",
        "primary-fixed-dim": "#63ef82",
        "outline": "#568061",
        "surface-dim": "#a0e4b1",
        "primary-container": "#72fe8f",
        "on-primary": "#cfffcf",
        "surface": "#ddffe2",
        "on-primary-fixed-variant": "#006a2b",
        "on-secondary-container": "#004b75",
        "surface-container-highest": "#acecbb",
        "surface-container-low": "#cafdd4",
        "background": "#ddffe2",
        "surface-tint": "#006a2b",
        "on-tertiary-container": "#584000",
        "tertiary-dim": "#674b00",
        "tertiary-container": "#fec330",
        "inverse-surface": "#001205",
        "inverse-on-surface": "#7ca785",
        "secondary-container": "#acd6ff",
        "primary-fixed": "#72fe8f",
        "on-surface": "#0b361d",
        "on-error-container": "#520c00",
        "primary-dim": "#005d25",
        "tertiary-fixed-dim": "#efb520",
        "on-tertiary-fixed": "#402d00",
        "error-container": "#f95630",
        "on-surface-variant": "#3b6447",
        "error": "#b02500",
        "secondary-dim": "#005482",
        "on-secondary-fixed": "#003758",
        "on-error": "#ffefec",
        "tertiary-fixed": "#fec330",
        "on-tertiary-fixed-variant": "#634900",
        "tertiary": "#765600",
        "secondary-fixed": "#acd6ff",
        "on-secondary-fixed-variant": "#005584",
        "on-tertiary": "#fff1db",
        "on-background": "#0b361d",
        "surface-container": "#bef5c9",
        "error-dim": "#b92902",
        "surface-bright": "#ddffe2",
        "on-primary-fixed": "#004a1c",
        "outline-variant": "#8bb795",
        "surface-variant": "#acecbb",
        "primary": "#006a2b",
        "inverse-primary": "#72fe8f",
        "surface-container-lowest": "#ffffff",
        "on-secondary": "#ebf3ff",
      },
      fontFamily: {
        "headline": ["Plus Jakarta Sans", "sans-serif"],
        "body": ["Lexend", "sans-serif"],
        "label": ["Lexend", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
    },
  },
  plugins: [],
}
